### ISSUE TITLE
Feature request: allow toggling of web client stat block

### ISSUE THREAD

**Issue by montver** [bekriebel/fvtt-module-avclient-livekit#11]
Testing the experimental web client I have seen that the connection label and its status do not disappear. It would be interesting to be able to capture well with obs or other stream programs.
![grabilla em8212](https://user-images.githubusercontent.com/72754407/163880570-7add5289-50e0-4554-950a-6d3f94a85165.png)

**Comment by bekriebel** [comment]
That's a good request. I'll try to get it into an upcoming release.
