### ISSUE TITLE
Error connecting to LiveKit Server: Could not connect after timeout

### ISSUE THREAD

**Issue by Fmerrick** [bekriebel/fvtt-module-avclient-livekit#14]
I'm getting this error. Tried disabling/enabling, uninstall/reinstall, A/V disable/enable, resetting room ID. Tried both April and May key, no luck.

**Comment by bekriebel** [comment]
Can you double check that you are using the address `livekit.tavern.at` exactly as-is? There should be no `https://` or any other prefix before it.

If that is correct, can you try opening a new tab in your browser and going to "https://livekit.tavern.at/" - if it is working, you should see "OK". If it isn't, perhaps you will get some additional information.

**Comment by Fmerrick** [comment]
I'm getting an 'OK' there. Sorry for posting in multiple places, I probably should have just gone to Discord!

**Comment by Fmerrick** [comment]
![Livekit](https://user-images.githubusercontent.com/64361933/167204235-2b158e1d-0ddf-4cb9-972e-b88f2a330d40.JPG)

**Comment by Fmerrick** [comment]
All cleared up, thanks!

**Comment by bekriebel** [comment]
For future reference, it seems like it may have been an overzealous ad blocker that caused the connection issues 🙂
