### ISSUE TITLE
could not get certificate from issuer

### ISSUE THREAD

**Issue by FumbleBe** [bekriebel/fvtt-module-avclient-livekit#18]
Hey Guys,

Have an issue with a docker install. Server is not reachable because of a certificate problem.

My caddy.yaml file look like this:

_logging:
  logs:
    default:
      level: INFO
storage:
  "module": "file_system"
  "root": "/data"
apps:
  tls:
    certificates:
      automate:
        - my.domain.com
        - my-turn.domain.com
  layer4:
    servers:
      main:
        listen: ["myip:4443"]
        routes:
          - match:
            - tls:
                sni:
                  - "my-turn.domain.com"
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial: ["localhost:5349"]
          - match:
              - tls:
                  sni:
                    - "my.domain.com"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["localhost:7880"]_

in the logs, I can see this:

`livekit-caddy-1    | {"level":"warn","ts":1653478049.9978166,"logger":"tls.issuance.zerossl","msg":"missing email address for ZeroSSL; it is strongly recommended to set one for next time"}
livekit-caddy-1    | {"level":"info","ts":1653478050.5979583,"logger":"tls.issuance.zerossl","msg":"generated EAB credentials","key_id":"W1Z-EeZfRNAl9kgagwpwLQ"}
livekit-caddy-1    | {"level":"info","ts":1653478050.637031,"logger":"tls.issuance.zerossl","msg":"generated EAB credentials","key_id":"IqpDiu4818OQ3rjgaL1IRw"}
livekit-caddy-1    | {"level":"info","ts":1653478089.7407851,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"my.domain.com","challenge_type":"http-01","ca":"https://acme.zerossl.com/v2/DV90"}
livekit-caddy-1    | {"level":"info","ts":1653478092.3227298,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"my-turn.domain.com","challenge_type":"http-01","ca":"https://acme.zerossl.com/v2/DV90"}
livekit-caddy-1    | {"level":"error","ts":1653478408.2324898,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"my.domain.com","issuer":"acme.zerossl.com-v2-DV90","error":"[my.domain.com] solving challenges: [my.domain.com] authorization took too long (order=https://acme.zerossl.com/v2/DV90/order/wXCjaBtEI_yqZEo-gUk1ZA) (ca=https://acme.zerossl.com/v2/DV90)"}
livekit-caddy-1    | {"level":"error","ts":1653478408.2386186,"logger":"tls.renew","msg":"will retry","error":"[my.domain.com] Renew: [my.domain.com] solving challenges: [my.domain.com] authorization took too long (order=https://acme.zerossl.com/v2/DV90/order/wXCjaBtEI_yqZEo-gUk1ZA) (ca=https://acme.zerossl.com/v2/DV90)","attempt":8,"retrying_in":1800,"elapsed":6427.744908641,"max_duration":2592000}
livekit-caddy-1    | {"level":"error","ts":1653478421.5916631,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"my.domain.com","issuer":"acme.zerossl.com-v2-DV90","error":"[my.domain.com] solving challenges: [my.domain.com] authorization took too long (order=https://acme.zerossl.com/v2/DV90/order/Lz58_UobIO174yjmzfwGhw) (ca=https://acme.zerossl.com/v2/DV90)"}
livekit-caddy-1    | {"level":"error","ts":1653478421.591736,"logger":"tls.renew","msg":"will retry","error":"[my-turn.domain.com] Renew: [my-turn.domain.com] solving challenges: [my-turn.domain.com] authorization took too long (order=https://acme.zerossl.com/v2/DV90/order/Lz58_UobIO174yjmzfwGhw) (ca=https://acme.zerossl.com/v2/DV90)","attempt":8,"retrying_in":1800,"elapsed":6441.087561022,"max_duration":2592000`

Not quite sure how to solve this the right way. Any help appreciated

**Comment by bekriebel** [comment]
I'm not quite sure what would cause it, but it looks like your domain isn't properly configured somewhere in your environment. From the logs, it's trying to generate a certificate for `my.domain.com` and `my-turn.domain.com`. I would check your config files and how you are running things and try to figure out where your domain isn't getting set.

**Comment by FumbleBe** [comment]
I forgot to anonymise my domain name in my conf file in my previous post. my.domain.com and my-turn.domain.com are dummy name for the one in my config file. logs are correct, they match the real domain name.
Thanks for your help
