### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by Argonaut13** [bekriebel/fvtt-module-avclient-livekit#22]
I find the video feed constantly flickers. The audio is crisp and clear, but the video tends to be distracting.

Is this a Livekit issue or perhaps the module?

**Comment by bekriebel** [comment]
I haven't had other reports of this. Does the flickering happen during any specific action? Muting/unmuting, use of Push-to-talk, etc?

**Comment by bekriebel** [comment]
I haven't seen a response to this, so I'm going to go ahead and close the issue. If it is still occurring, please let me know.
