### ISSUE TITLE
Foundry v10 Stable Dock Position Disabled

### ISSUE THREAD

**Issue by Dick-K** [bekriebel/fvtt-module-avclient-livekit#28]
Hi,

I've just updated a test instance of Foundry to v10 stable. At the last minute thay included a L/R/T/B dock position selector in Audio/Video Configuration. Using Livekit 0.5.10 renders the selector invisible. Any chance this can be reversed?

cheers and thanks!

**Comment by bekriebel** [comment]
Thanks for reporting! I'm just now updating my servers and I'll work on fixing it ASAP.

**Comment by Dick-K** [comment]
Quick work! Thanks, have updated LiveKit and can confirm fix.
