### ISSUE TITLE
can you do a guide on how to setup our own livekit server

### ISSUE THREAD

**Issue by GamerKing122** [bekriebel/fvtt-module-avclient-livekit#30]
can you do a guide on how to setup our own livekit server as their guide dont specificly tell you how to do it for your module thx

**Comment by bekriebel** [comment]
There's nothing specific to the module that is needed for a LiveKit deployment, so the guides from LiveKit will work as-is. There's also some user created guides on our Wiki that are more geared to FoundryVTT that may be helpful. 
https://github.com/bekriebel/fvtt-module-avclient-livekit/wiki

I updated the README to link to the wiki as well.
