### ISSUE TITLE
Share audio browser tab

### ISSUE THREAD

**Issue by brunocalado** [bekriebel/fvtt-module-avclient-livekit#33]
Hi!

This is alternative solution for [24](https://github.com/bekriebel/fvtt-module-avclient-livekit/issues/24)

Is it possible to get the tracks with this livekit feature?
https://docs.livekit.io/recipes/share-audio-browser-tab/

This is very useful for streamers. 

Tks

**Comment by bekriebel** [comment]
This feature is for sharing into the LiveKit stream, not out of the LiveKit stream. This is already available as an unsupported feature (I use this for my own testing purposes). You can open the developer console and run `await game.webrtc.client._liveKitClient.shareScreen(true);` to start the sharing process.

It can also be set as an FVTT Script macro:

![image](https://user-images.githubusercontent.com/183779/192037756-0e152476-554d-4c05-a4a8-e57aeeef637c.png)

Setting the value to `false` stops the sharing.
