### ISSUE TITLE
permanent option to display character name instead of playernames

### ISSUE THREAD

**Issue by dinotheextinct** [bekriebel/fvtt-module-avclient-livekit#41]
As written in the title, I would like to know if there is a possibility to set the names below the videostreams to the character names instead of the player names permanently.

**Comment by bekriebel** [comment]
Yes, this is part of foundry core. Under the A/V settings, you can set the nameplate to be only the character name.
![image](https://user-images.githubusercontent.com/183779/213544908-94e12d48-7605-4d0a-8759-9cf370352b70.png)
