### ISSUE TITLE
Сould not establish pc connection

### ISSUE THREAD

**Issue by Dipod** [bekriebel/fvtt-module-avclient-livekit#57]
This issue occurs on Windows 11 Pro 21H2

In this browsers:

- Google Chrome 114.0.5735.199 64-bit
- Microsoft Edge 114.0.1823.58 64-bit
- FLC 3.1.0

foundry.js:59246 Disconnected from LiveKit A/V Server
fetch @ foundry.js:59246

LiveKitAVClient.ts:351 LiveKitAVClient | Could not connect: Error: could not establish pc connection
at livekit-client.esm.mjs:21878:16

connect @ LiveKitAVClient.ts:351
foundry.js:59246 Error connecting to LiveKit Server: could not establish pc connection

But in Firefox 114.0.2 64-bit all works fine.

I use self-hosted LiveKit server

**Comment by Dipod** [comment]
Resolved issue. Needed port forvarding for TCP port 7881

**Comment by boy51** [comment]
For reference for me it was an issue with TURN server
