### ISSUE TITLE
You cannot enable your microphone because you do not have permission to broadcast your audio feed

### ISSUE THREAD

**Issue by marmitejim** [bekriebel/fvtt-module-avclient-livekit#6]
Hi there - hope you had a good Xmas.

Some (but not all) of my players are unable to broadcast sound. 

When you click on enable audio they get the message:-
"You cannot enable your microphone because you do not have permission to broadcast your audio feed"

This occurs when either this module or your jitsi module is enabled. But I haven't tried any other audio/visual solutions so its possibly nothing to do with your module/s at all!

But if you have any idea where the problem lies your help would be much appreciated

It occurred directly after switching from the beta.meet.jit.si server to meet.jit.si

![image](https://user-images.githubusercontent.com/5129352/147781634-ae005ba3-d49f-49a3-815b-1383998367e3.png)

**Comment by bekriebel** [comment]
What version of Foundry are you on when you get this?

Two things to check:
1. If, as the GM, you have selected Block User Audio on a user, that will remove their permission from broadcasting audio. If this is the case, the GM needs to click Allow User Audio for that user:
![image](https://user-images.githubusercontent.com/183779/147782168-08ddb738-a530-4b0e-8ee0-1f0dfcea7486.png)
![image](https://user-images.githubusercontent.com/183779/147782224-b5a404a5-0248-4c0f-8c7e-88e0a1845d07.png)
2. By default, the "Player" role does not have permission to broadcast audio or video. If your users have the Player role, you need to also set the permission to Allow Broadcasting Audio / Video under the permission configuration, or give them the Trusted Player role.
![image](https://user-images.githubusercontent.com/183779/147782312-866a08f1-3735-4ba7-bac9-4cf90b8d3c79.png)

I'm betting it is one of these two things, but if not please let me know!

**Comment by marmitejim** [comment]
Ah thanks! It was the former.

I recall now we had problems connecting on the jitsi server so we all connected to jitsi in a seperate window and of course there was feedback.

Sorry to pester you with a question that had nothing to do with your module.

Really appreciate your help

Looking forward to using the Livekit module at our next game session

**Comment by bekriebel** [comment]
Glad that worked out!
