### ISSUE TITLE
Error with adblock

### ISSUE THREAD

**Issue by AsterITA** [bekriebel/fvtt-module-avclient-livekit#8]
Hi, I wanted to report that the module doesn't work with an adblock, by disabling it it works again without any problems.

Using the module with Ublock Origin I get the following error:

```
LiveKitAVClient | Could not connect: Error: Internal error
    i errors.js:6
    <anonymous> errors.js:13
    onerror SignalClient.js:69
    a SignalClient.js:5
LiveKitAVClient.ts:255:16
    connect LiveKitAVClient.ts:255
```

**Comment by bekriebel** [comment]
I'm not able to reproduce this. I keep uBlock Origin on my browser as well, and it doesn't seem to be blocking anything. I tried with two different instances of Foundry. Are you able to click into SignalClient.js and see what line it is triggering on?

**Comment by AsterITA** [comment]
Yes, it triggers on line 69 with ` reject(new errors_1.ConnectionError('Internal error'));` and line 5 with ` function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }`.

The same error was encounted by two friends of mine too, it was always resolved by disabling ublock origin on the page.

**Comment by bekriebel** [comment]
Huh... Looks like that's coming from this part of the code: https://github.com/livekit/client-sdk-js/blob/ac95ada5e4e1f90c6560e63603bedc5320e85a1f/src/api/SignalClient.ts#L160

I just double checked and there isn't any kind of ads or metrics happening, it's just an attempt to connect to the websocket. I'm not sure why ublock is causing an error for you; like I said, I haven't been able to reproduce that.

I'd recommend adding a whitelist for the address. You can double check the source, but I don't think there's any valid reason why ublock should stop the connection, unless it just tries to stop all websocket sessions.

**Comment by AsterITA** [comment]
I figured out why it's happening, it seems that ublock origin is blocking the duckdns domain, my livekit server it's there so it's blocking the connection. Just letting you know in case happens to someone else.
![immagine](https://user-images.githubusercontent.com/7688157/159153830-56ce00ea-6eef-489d-adbe-8665d04522f5.png)

**Comment by bekriebel** [comment]
Ahh, that makes sense. Thanks for following up!
