### ISSUE TITLE
Volume Setting for individual players resetting periodically/on relog of one palyer

### ISSUE THREAD

**Issue by kleelue** [bekriebel/fvtt-module-avclient-livekit#9]
Hey there,

we are joining with 2 Clients behind the same IP and my s/o need to turn me down, so he doesn't hear me through foundry. Sadly, his Volume resets periodically, so he can't mute me. We disabled Adblock (Adguard), but it always resets after a litte while, when someone relogs, .... 
Is there a way to get a "mute player" functionality, so someone can mute one specific player for themselves, but not for everyone else? Or just get it so the Volume doesn't reset. We are Using your AVKit Server through patreon, so there shouldn't be a problem, I think (:

Luette

**Comment by bekriebel** [comment]
Huh... I wasn't aware of an issue with the volume slider. I'll try to test this out. If you have any other information on when this is happens, please let me know!

**Comment by bekriebel** [comment]
Thanks for reporting this! I have reproduced the issue and I think I know what the problem is. I should be able to get this resolved soon.
